services:
  database:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: measure
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: test
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -u rodrigo --password=test']
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/backend
      - /backend/node_modules
    command: ['npm', 'run', 'dev']
volumes:
  data: {}
