version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    depends_on:
      - database
    volumes:
      - ./:/app
    command: ['npm', 'run', 'dev']

  database:
    image: mysql:9
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: measure
      MYSQL_USER: measure_user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql

volumes:
  data: {}
